#include "lvgl.h"

#define CUSTOM_SYMBOL_SOLID_SHIELD_VIRUS "\xEE\x81\xAC"
#define CUSTOM_SYMBOL_SOLID_VIRUS "\xEE\x81\xB4"
#define CUSTOM_SYMBOL_SOLID_VIRUS_SLASH "\xEE\x81\xB5"
#define CUSTOM_SYMBOL_SOLID_VIRUSES "\xEE\x81\xB6"
#define CUSTOM_SYMBOL_SOLID_CALENDAR_ALT "\xEF\x81\xB3"
#define CUSTOM_SYMBOL_SOLID_LIGHTBULB "\xEF\x83\xAB"
#define CUSTOM_SYMBOL_SOLID_CALENDAR_PLUS "\xEF\x89\xB1"
#define CUSTOM_SYMBOL_SOLID_CALENDAR_MINUS "\xEF\x89\xB2"
#define CUSTOM_SYMBOL_SOLID_CALENDAR_TIMES "\xEF\x89\xB3"
#define CUSTOM_SYMBOL_SOLID_CALENDAR_CHECK "\xEF\x89\xB4"
#define CUSTOM_SYMBOL_SOLID_CLIPBOARD_LIST "\xEF\x91\xAD"
#define CUSTOM_SYMBOL_SOLID_FAN "\xEF\xA1\xA3"

extern lv_font_t custom_symbols_solid;